services:
  gridwise:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: gridwise-api

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: production
      PORT: 3000
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GEMINI_MODEL: ${GEMINI_MODEL:-gemini-2.5-flash}

    restart: unless-stopped